### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by jaybox15** [Mowjoh/Meteor-Skin-Library#13]
Whenever I start the program, I get this error message: 
![capture](https://cloud.githubusercontent.com/assets/25990636/23279603/e9513484-f9e3-11e6-92b3-2ae227e97998.PNG)

I wanted to know if I was doing something wrong, the updater doesn't work either.

**Comment by Mowjoh** [comment]
Hi ! 
This is not a bug. 
This is not something you did wrong, 
It's just that I changed web domains, so the app was looking at lunaticfox.com when it now is mowjoh.com

Since lunaticfox doesn't host anything anymore, the errors show on MSL.
(it won't change what the app can do, well except use the updater)
